
name: Doxygen Action
  
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v3

    # Generate documentation with Doxygen
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.3.0
      with:
        doxyfile-path: "./Doxyfile"
        working-directory: "."

    # Debug: List files to verify Doxygen output
    - name: List files after Doxygen run
      run: ls -R

    # Deploy documentation to gh-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html # Match OUTPUT_DIRECTORY in Doxyfile
        destination_branch: gh-pages